---

# Set these variables if you wish to use the upstream nginx.org repositories. 
# Leave them disabled to use distribution supplied nginx. use_nginx_mainline 
# will have no effect without use_nginx_repo. 
nginx_upstream_repo: no
nginx_mainline: no

# Variables used in top level nginx.conf and filesystem configuration. 
nginx_sites_enabled: /etc/nginx/sites-enabled 
nginx_sites_available: /etc/nginx/sites-available
nginx_worker_processes: "1"
nginx_error_log: /var/log/nginx/error.log
nginx_error_log_level: warn
nginx_pid: /var/run/nginx.pid
nginx_worker_connections: 1024
nginx_default_type: application/octet-stream
nginx_log_format_name: main
nginx_log_format: | 
 '$remote_addr - $remote_user [$time_local] "$request" '
 '$status $body_bytes_sent "$http_referer" '
 '"$http_user_agent" "$http_x_forwarded_for"'
nginx_access_log: /var/log/nginx/access.log
nginx_access_log_format: main
nginx_sendfile: "on"
nginx_tcp_nopush: "off"
nginx_keepalive_timeout: 65
nginx_gzip: "off"

nginx_upstream_servers:
  - server:
      file_name: "php-fpm.conf"
      upstream: {name: "phpcgi_www", type: "server", destination: "unix:/var/run/php/php7.0-fpm.sock"}

nginx_sites:
  - server:
      file_name: default.conf
      ports: 
        - "80"
        - "443 ssl"
      server_name: www.example.com
      root: "/home/app/wordpress"
      index: "index.html index.php"
      access_log: /var/log/nginx/app-access.log
      error_log: /var/log/nginx/app-error.log notice
      locations1: {name: "~ \\.php", 
                   include: "fastcgi_params", 
                   fastcgi_param: "SCRIPT_FILENAME    $document_root$fastcgi_script_name",
                   fastcgi_pass: "phpcgi_www",
                   fastcgi_send_timeout: "75s",
                   fastcgi_read_timeout: "180s",
                   fastcgi_connect_timeout: "75s"}