---

- name: Add group "wordpress"
  group: name=wordpress

- name: Add user "wordpress"
  user: name=wordpress group=wordpress home={{ wp_home }}

- name: Create log directory
  file: path={{ wp_home }}/logs/ state=directory

- name: Download WordPress
  get_url: url=https://wordpress.org/{{ wp_package }} dest={{ wp_home }}/{{ wp_package }}

- name: Extract archive
  command: chdir={{ wp_home }} /bin/tar xvf {{ wp_package }} creates={{ wp_home }}/wordpress

- name: Fetch random salts for WordPress config
  local_action: command curl https://api.wordpress.org/secret-key/1.1/salt/
  register: "wp_salt"
  become: no
  become_method: sudo

- name: Copy WordPress config file
  template: src=wp-config.php.j2 dest={{ wp_home }}/wordpress/wp-config.php

- name: Copy WordPress nginx config
  template: src=site.conf.j2 dest=/etc/nginx/sites-available/default.conf

- name: Change ownership of WordPress installation
  file: path={{ wp_home }} owner=wordpress group=wordpress state=directory recurse=yes

- name: Restart php-fpm Service
  service: name=php7.0-fpm state=restarted enabled=yes
